# Generated by Django 3.1.7 on 2021-03-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_disslikepost_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disslikepost',
            old_name='like_comment',
            new_name='like_post',
        ),
        migrations.RenameField(
            model_name='likepost',
            old_name='like_comment',
            new_name='like_post',
        ),
    ]
