# Generated by Django 3.1.7 on 2021-03-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210305_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disslikecomment',
            old_name='like_comment',
            new_name='DisslikeComment',
        ),
        migrations.RenameField(
            model_name='disslikepost',
            old_name='like_post',
            new_name='Disslike_post',
        ),
    ]
